name: Build Blog on Markdown Changes

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'blog/posts_md/**/*.md'
      - 'blog/app/**/*'
      - 'blog/public/images/**/*'   # ← commonly this, not app/public
      - 'blog/package*.json'
      - 'blog/next.config.js'
      - 'blog/tailwind.config.js'
      - 'blog/postcss.config.js'
  workflow_dispatch:

permissions:
  contents: write   # needed to push back to the repo

jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'blog/package-lock.json'

      - name: Install dependencies
        working-directory: ./blog
        run: npm ci

      - name: Build blog
        working-directory: ./blog
        run: npm run build

      - name: Commit and push built files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog/posts/
          git add blog/public/images/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-build blog from markdown changes [skip ci]"
          git push
